name: Build Jar

on:
  push:
    tags:
      - "v*.*"

jobs:
  build:

    runs-on: windows-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'

    - name: Build Java
      shell: cmd
      run: |
        call CompileMarsClass.bat

    - name: Package jar file
      shell: cmd
      run: |
        call CreateMarsJar.bat
        rename Mars.jar Mars_CO_${{  github.ref_name }}.jar

    - name: Zip test file
      shell: cmd
      run: |
        cd test
        python -u zipTestClass.py MarsTest.zip
        move MarsTest.zip ..\Mars_Test_CO_${{  github.ref_name }}.zip
        cd ..

    - name: pre test
      shell: cmd
      run: |
        copy Mars_CO_${{  github.ref_name }}.jar test\mars.jar

    - name: Test1
      shell: cmd
      run: |
        cd test
        java -jar mars.jar code1.asm nc mc CompactLargeText coL1 cl bhelbal.class ig > testTemp.txt
        fc testTemp.txt stdout1.txt

    - name: Test2
      shell: cmd
      run: |
        cd test
        java -jar mars.jar a code2.asm mc CompactLargeText ig dump .text HexText testTemp.txt
        fc testTemp.txt stdout2.txt

    - name: Test3
      shell: cmd
      run: |
        cd test
        java -jar mars.jar code3.asm mc CompactLargeText nc db coL1 > testTemp.txt
        fc testTemp.txt stdout3.txt

    - name: Test4
      shell: cmd
      run: |
        cd test
        java -jar mars.jar code_cc.asm nc mc CompactLargeText cc ccw 2.0:1.0:1.0:1.0:0.5 > testTemp.txt
        fc testTemp.txt stderr_cc2.txt

    - name: Test5
      shell: cmd
      run: |
        cd test
        java -jar mars.jar code_cc.asm nc mc CompactLargeText cc > testTemp.txt
        fc testTemp.txt stderr_cc1.txt

    - name: Create a release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          Mars_CO_${{  github.ref_name }}.jar
          Mars_Test_CO_${{  github.ref_name }}.zip
        draft: true
